/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Landmark } from './utils';

// =========================================================================
// KROATIEN REISEBEGLEITER - VOLLSTÄNDIGER POI-KATALOG FÜR 25 KM RADIUS FILTER
// Kategorien:
// - Städte (Immer auf der Karte markiert)
// - Sehenswürdigkeiten (UNESCO, Altstädte, Schlösser, Burgen)
// - Attraktionen (Skywalk, Panoramen, Seilbahnen, Meeresorgel)
// - Denkmäler & Kultur (Kathedralen, Statuen, Kulturdenkmäler)
// - Seen & Gewässer (Nationalparks, Seen, Wasserfälle)
// - Berge & Gipfel (Aussichtsgipfel & Gebirgszüge)
// - Strände (Badebuchten & Adria-Strände)
// - Freizeitparks (Wasserparks, Dinoparks, Erlebnisse mit Preisen & Zeiten)
// - Schwimmbäder & Thermen (Thermen, Hallenbäder mit Preisen & Zeiten)
// - Tankstellen (Infrastruktur mit aktuellen Benzinpreisen & 24h-Service)
// - Krankenhäuser (Infrastruktur mit 24/7 Notaufnahme & Notrufnummern)
// - Apotheken (Infrastruktur mit Öffnungszeiten & Notdienst-Info)
// - Polizeireviere (Infrastruktur mit Dienststellen & Notruf 192)
// =========================================================================

export const ALL_CROATIA_POIS: Landmark[] = [
  // ==================== STÄDTE (Immer eingeblendet) ====================
  {
    id: 'city-dubrovnik',
    name: 'Dubrovnik (Altstadt)',
    placeId: 'ChIJ2-9_4W8vThMR_8w82mR1k1s',
    lat: 42.6412,
    lng: 18.1084,
    altitude: 20,
    heading: 140,
    tilt: 55,
    camAltitude: 90,
    camRange: 400,
    camTilt: 55,
    camHeading: 140,
    category: 'Städte',
    description: 'Die weltberühmte Perle der Adria mit vollständig erhaltener Festungsmauer, weißem Marmorpflaster (Stradun) und reicher Geschichte der Republik Ragusa.',
    highlights: ['UNESCO-Weltkulturerbe', 'Stradun Flaniermeile', 'Mittelalterliche Festungsmauern'],
    iconName: 'city',
    pinColor: '#0284c7',
    glyph: '🏙️',
    openingHours: 'Öffentlicher Raum, 24/7 zugänglich',
    prices: 'Freier Zugang zur Altstadt (Stadtmauer separat)',
    cityId: 'dubrovnik'
  },
  {
    id: 'city-split',
    name: 'Split (Zentrum & Riva)',
    placeId: 'ChIJO3VfN28vThMRq_H63Xn4d9Q',
    lat: 43.5081,
    lng: 16.4402,
    altitude: 15,
    heading: 200,
    tilt: 56,
    camAltitude: 85,
    camRange: 420,
    camTilt: 56,
    camHeading: 200,
    category: 'Städte',
    description: 'Die zweitgrößte Stadt Kroatiens, pulsierendes Herz Dalmatiens mit dem 1.700 Jahre alten Palast des römischen Kaisers Diokletian und der sonnigen Riva-Palmenpromenade.',
    highlights: ['Diokletianpalast (UNESCO)', 'Riva Palmenpromenade', 'Marjan Aussichtshügel'],
    iconName: 'city',
    pinColor: '#0284c7',
    glyph: '🏙️',
    openingHours: '24/7 lebendige Altstadt',
    prices: 'Freier Zugang zur Altstadt & Riva',
    cityId: 'split'
  },
  {
    id: 'city-zadar',
    name: 'Zadar (Historische Halbinsel)',
    placeId: 'ChIJm7_f5W8vThMRo_H63Xn4d9Z',
    lat: 44.1160,
    lng: 15.2280,
    altitude: 15,
    heading: 260,
    tilt: 55,
    camAltitude: 90,
    camRange: 450,
    camTilt: 55,
    camHeading: 260,
    category: 'Städte',
    description: 'Historische Stadt auf einer Halbinsel, berühmt für das römische Forum, die romanische Donatus-Kirche und den laut Alfred Hitchcock schönsten Sonnenuntergang der Welt.',
    highlights: ['Meeresorgel & Sonnengruß', 'Römisches Forum', 'Rundkirche St. Donatus'],
    iconName: 'city',
    pinColor: '#0284c7',
    glyph: '🏙️',
    openingHours: '24/7 zugänglich',
    prices: 'Kostenlose Erkundung',
    cityId: 'zadar'
  },
  {
    id: 'city-zagreb',
    name: 'Zagreb (Hauptstadt & Ban-Jelačić-Platz)',
    placeId: 'ChIJO3VfN28vThMRq_H63Xn4d9G',
    lat: 45.8131,
    lng: 15.9775,
    altitude: 120,
    heading: 10,
    tilt: 54,
    camAltitude: 180,
    camRange: 500,
    camTilt: 54,
    camHeading: 10,
    category: 'Städte',
    description: 'Die charmante mitteleuropäische Hauptstadt Kroatiens mit malerischer Oberstadt (Gornji Grad), pulsierender Unterstadt, Cafékultur und grünen Alleen.',
    highlights: ['Ban-Jelačić-Hauptplatz', 'Standseilbahn zur Oberstadt', 'Gotische Kathedrale'],
    iconName: 'city',
    pinColor: '#0284c7',
    glyph: '🏙️',
    openingHours: '24/7 belebt',
    prices: 'Kostenlos',
    cityId: 'zagreb'
  },
  {
    id: 'city-rovinj',
    name: 'Rovinj (Istrische Altstadtperle)',
    placeId: 'ChIJ2-9_4W8vThMR_8w82mR1k1R',
    lat: 45.0818,
    lng: 13.6325,
    altitude: 25,
    heading: 290,
    tilt: 50,
    camAltitude: 95,
    camRange: 380,
    camTilt: 50,
    camHeading: 290,
    category: 'Städte',
    description: 'Venezianisch geprägte Halbinselstadt in Istrien mit kopfsteingepflasterten Künstlergassen, pastellfarbenen Häusern und der Kathedrale der Hl. Euphemia.',
    highlights: ['Venezianischer Glockenturm', 'Künstlergasse Grisia', 'Malerischer Fischerhafen'],
    iconName: 'city',
    pinColor: '#0284c7',
    glyph: '🏙️',
    openingHours: '24/7 zugänglich',
    prices: 'Freier Zugang',
    cityId: 'rovinj'
  },
  {
    id: 'city-pula',
    name: 'Pula (Antike Hafenstadt)',
    placeId: 'ChIJO3VfN28vThMRq_H63Xn4d9P',
    lat: 44.8732,
    lng: 13.8475,
    altitude: 20,
    heading: 340,
    tilt: 52,
    camAltitude: 100,
    camRange: 420,
    camTilt: 52,
    camHeading: 340,
    category: 'Städte',
    description: 'Südspitze Istriens mit einem der besterhaltenen römischen Amphitheater der Welt, antiken Tempeln und lebendiger Seefahrertradition.',
    highlights: ['Römisches Amphitheater', 'Augustus-Tempel am Forum', 'Sergierbogen'],
    iconName: 'city',
    pinColor: '#0284c7',
    glyph: '🏙️',
    openingHours: '24/7 zugänglich',
    prices: 'Freier Zugang zur Stadt',
    cityId: 'pula'
  },
  {
    id: 'city-sibenik',
    name: 'Šibenik (Königsstadt am Krka-Kanal)',
    placeId: 'ChIJO3VfN28vThMRq_H63Xn4d9S',
    lat: 43.7350,
    lng: 15.8952,
    altitude: 25,
    heading: 50,
    tilt: 52,
    camAltitude: 95,
    camRange: 420,
    camTilt: 52,
    camHeading: 50,
    category: 'Städte',
    description: 'Älteste von Kroaten gegründete Stadt an der Adria, geschützt von vier mächtigen Festungen und berühmt für die gotisch-renaissance Kathedrale des Hl. Jakob.',
    highlights: ['St. Jakob Kathedrale (UNESCO)', '4 venezianische Festungen', 'Verwinkelte Steingassen'],
    iconName: 'city',
    pinColor: '#0284c7',
    glyph: '🏙️',
    openingHours: '24/7 zugänglich',
    prices: 'Freier Zugang',
    cityId: 'sibenik'
  },
  {
    id: 'city-makarska',
    name: 'Makarska (Riviera-Zentrum)',
    placeId: 'ChIJO3VfN28vThMRq_H63Xn4d9M',
    lat: 43.2965,
    lng: 17.0182,
    altitude: 15,
    heading: 75,
    tilt: 52,
    camAltitude: 90,
    camRange: 450,
    camTilt: 52,
    camHeading: 75,
    category: 'Städte',
    description: 'Mittelpunkt der Makarska Riviera, eingebettet zwischen türkisblauen Buchten und dem majestätisch auf 1.762 m aufragenden Biokovo-Gebirge.',
    highlights: ['Palmenpromenade Makarska', 'Kačić-Platz & Barockkirche', 'Biokovo-Gebirgskulisse'],
    iconName: 'city',
    pinColor: '#0284c7',
    glyph: '🏙️',
    openingHours: '24/7 zugänglich',
    prices: 'Freier Zugang',
    cityId: 'makarska'
  },
  {
    id: 'city-hvar',
    name: 'Hvar Stadt (Insel-Juwel)',
    placeId: 'ChIJO3VfN28vThMRq_H63Xn4d9H',
    lat: 43.1729,
    lng: 16.4428,
    altitude: 15,
    heading: 310,
    tilt: 50,
    camAltitude: 85,
    camRange: 400,
    camTilt: 50,
    camHeading: 310,
    category: 'Städte',
    description: 'Sonnigste Inselstadt Kroatiens mit gotischen Palästen, dem größten Marktplatz Dalmatiens und Blick auf die vorgelagerten Pakleni-Inseln.',
    highlights: ['Spanische Festung Fortica', 'Hauptplatz Pjaca', 'Pakleni-Inseln Panorama'],
    iconName: 'city',
    pinColor: '#0284c7',
    glyph: '🏙️',
    openingHours: '24/7 zugänglich',
    prices: 'Freier Zugang',
    cityId: 'hvar'
  },

  // ==================== BERGE & GIPFEL ====================
  {
    id: 'berg-biokovo-sveti-jure',
    name: 'Sveti Jure (Biokovo-Gipfel, 1.762 m)',
    placeId: 'ChIJ5533xP41RkcR-x9A7w-0Nkz',
    lat: 43.3428,
    lng: 17.0542,
    altitude: 1762,
    heading: 210,
    tilt: 60,
    camAltitude: 1950,
    camRange: 800,
    camTilt: 60,
    camHeading: 210,
    category: 'Berge',
    description: 'Der zweithöchste Berggipfel Kroatiens und höchste Punkt Dalmatiens. Bei klarer Sicht reicht der Blick über die gesamte Adria bis nach Italien (Monte Gargano).',
    highlights: ['1.762 m Höhe über dem Meer', 'Höchste befahrbare Asphaltstraße Kroatiens', 'Spektakuläre Fernsicht bis Italien'],
    iconName: 'mountain',
    pinColor: '#16a34a',
    glyph: '⛰️',
    openingHours: 'Naturpark-Straße: Täglich 07:00 - 20:00 Uhr (saisonal)',
    prices: 'Naturpark-Ticket ca. 8 € pro Person inkl. Fahrzeug',
    cityId: 'makarska'
  },
  {
    id: 'berg-srd-dubrovnik',
    name: 'Berg Srđ (Dubrovnik Hausberg, 412 m)',
    placeId: 'ChIJJ1N_zW8vThMRJ2X83_L_m0k',
    lat: 42.6489,
    lng: 18.1106,
    altitude: 412,
    heading: 195,
    tilt: 58,
    camAltitude: 550,
    camRange: 600,
    camTilt: 58,
    camHeading: 195,
    category: 'Berge',
    description: 'Der markante Kalksteinrücken direkt hinter der Altstadt von Dubrovnik. Bietet den ikonischen Postkartenblick auf die Terrakottadächer und die Insel Lokrum.',
    highlights: ['412 Meter Aussichtshöhe', 'Festung Imperial (Museum des Heimatkriegs)', 'Erreichbar per Seilbahn, Wanderweg oder Auto'],
    iconName: 'mountain',
    pinColor: '#16a34a',
    glyph: '⛰️',
    openingHours: 'Gipfelplateau 24/7 frei zugänglich',
    prices: 'Gipfelbesuch kostenlos (Seilbahn: ca. 27 € Hin/Rück)',
    cityId: 'dubrovnik'
  },
  {
    id: 'berg-ucka-vojak',
    name: 'Vojak (Učka-Gipfel, 1.401 m)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nky',
    lat: 45.2861,
    lng: 14.1983,
    altitude: 1401,
    heading: 160,
    tilt: 58,
    camAltitude: 1600,
    camRange: 750,
    camTilt: 58,
    camHeading: 160,
    category: 'Berge',
    description: 'Der höchste Gipfel der Halbinsel Istrien im Naturpark Učka. Auf dem Gipfel steht ein steinerner Aussichtsturm aus dem Jahr 1911 mit Fernrohr.',
    highlights: ['1.401 m höchster Punkt Istriens', 'Historischer Steinturm mit Panorama', 'Blick auf Kvarner Bucht & Julische Alpen'],
    iconName: 'mountain',
    pinColor: '#16a34a',
    glyph: '⛰️',
    openingHours: 'Ganzjährig frei zugänglich',
    prices: 'Kostenlos',
    cityId: 'rovinj'
  },
  {
    id: 'berg-sljeme-zagreb',
    name: 'Sljeme (Medvednica-Gipfel Zagreb, 1.033 m)',
    placeId: 'ChIJJ1N_zW8vThMRJ2X83_L_m0z',
    lat: 45.9002,
    lng: 15.9472,
    altitude: 1033,
    heading: 180,
    tilt: 55,
    camAltitude: 1250,
    camRange: 650,
    camTilt: 55,
    camHeading: 180,
    category: 'Berge',
    description: 'Der Hausberg der Zagreber im Naturpark Medvednica mit Fernsehturm, Skipisten (Snow Queen Trophy) und urigen Berghütten mit Käsespezialitäten.',
    highlights: ['1.033 m Zagreber Panoramagipfel', 'Moderne Seilbahn (Žičara Sljeme)', 'Traditionelle Berghütten (Štrukli & Gulasch)'],
    iconName: 'mountain',
    pinColor: '#16a34a',
    glyph: '⛰️',
    openingHours: '24/7 frei zugänglich (Seilbahn: Mo-So 09:00 - 19:00 Uhr)',
    prices: 'Wandern kostenlos, Seilbahn ca. 10 €',
    cityId: 'zagreb'
  },
  {
    id: 'berg-vidova-gora',
    name: 'Vidova Gora (Brač-Gipfel, 778 m)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkb',
    lat: 43.2986,
    lng: 16.6214,
    altitude: 778,
    heading: 200,
    tilt: 56,
    camAltitude: 950,
    camRange: 650,
    camTilt: 56,
    camHeading: 200,
    category: 'Berge',
    description: 'Höchster Berggipfel aller kroatischen Adriainseln. Bietet einen atemberaubenden Tiefblick auf die berühmte Hornspitze von Zlatni Rat und nach Hvar.',
    highlights: ['778 m höchste Inselerhebung der Adria', 'Tiefblick auf den Strand Zlatni Rat', 'Gipfelkreuz und urige Taverne'],
    iconName: 'mountain',
    pinColor: '#16a34a',
    glyph: '⛰️',
    openingHours: 'Ganzjährig frei zugänglich',
    prices: 'Kostenlos',
    cityId: 'hvar'
  },

  // ==================== SEEN & GEWÄSSER ====================
  {
    id: 'seen-plitvice-veliki-slap',
    name: 'Plitvicer Seen & Großer Wasserfall (78 m)',
    placeId: 'ChIJJ1N_zW8vThMRJ2X83_L_m0p',
    lat: 44.9022,
    lng: 15.6083,
    altitude: 580,
    heading: 320,
    tilt: 58,
    camAltitude: 720,
    camRange: 550,
    camTilt: 58,
    camHeading: 320,
    category: 'Seen & Gewässer',
    description: '16 kaskadenförmig verbundene smaragdgrüne Seen mit Travertin-Barrieren und Kroatiens höchstem Wasserfall (Veliki Slap). Ältester Nationalpark des Landes.',
    highlights: ['16 türkisfarbene Kaskadenseen', '78 Meter hoher Veliki Slap', 'UNESCO-Weltnaturerbe seit 1979'],
    iconName: 'water',
    pinColor: '#0284c7',
    glyph: '💧',
    openingHours: 'Täglich 07:00 - 20:00 Uhr (Eingänge 1 & 2)',
    prices: 'Erwachsene: ca. 24 € - 40 € (saisonal, inkl. Boot & Panoramazug), Kinder unter 7 frei',
    cityId: 'plitvice'
  },
  {
    id: 'seen-krka-skradinski-buk',
    name: 'Krka-Wasserfälle (Skradinski Buk)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nka',
    lat: 43.8048,
    lng: 15.9642,
    altitude: 45,
    heading: 45,
    tilt: 55,
    camAltitude: 120,
    camRange: 450,
    camTilt: 55,
    camHeading: 45,
    category: 'Seen & Gewässer',
    description: 'Eine der schönsten Travertin-Kaskaden Europas mit 17 Stufen über 800 Meter Länge. Kristallklares Wasser fließt durch dichte Auenwälder und historische Mühlen.',
    highlights: ['17 Stufen über Travertinbarrieren', 'Historische Wassermühlen & Ethnodorf', 'Bootsausflüge zur Insel Visovac'],
    iconName: 'water',
    pinColor: '#0284c7',
    glyph: '💧',
    openingHours: 'Täglich 08:00 - 20:00 Uhr (Sommer)',
    prices: 'Erwachsene: ca. 20 € - 30 € (inkl. Boot Skradin), Kinder 7-18: ca. 12 €',
    cityId: 'sibenik'
  },
  {
    id: 'seen-vransko-jezero',
    name: 'Vransko Jezero (Größter Natursee Kroatiens)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkv',
    lat: 43.9042,
    lng: 15.5583,
    altitude: 2,
    heading: 140,
    tilt: 50,
    camAltitude: 90,
    camRange: 600,
    camTilt: 50,
    camHeading: 140,
    category: 'Seen & Gewässer',
    description: 'Mit 30,7 km² der größte natürliche See Kroatiens, direkt neben der Adria bei Biograd. Bedeutendes europäisches Vogelreservat mit Holzstegen und Aussichtspunkt Kamenjak.',
    highlights: ['Größter natürlicher See Kroatiens', 'Ornithologisches Reservat (über 250 Vogelarten)', 'Aussichtspunkt Kamenjak mit Inselpanorama'],
    iconName: 'water',
    pinColor: '#0284c7',
    glyph: '💧',
    openingHours: 'Naturpark-Infozentren: Täglich 08:00 - 20:00 Uhr',
    prices: 'Eintritt Naturpark & Holzsteg ca. 5 € pro Person',
    cityId: 'zadar'
  },
  {
    id: 'seen-bacina-seen',
    name: 'Baćina-Seen (Ploče / Makarska Riviera)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkc',
    lat: 43.0783,
    lng: 17.4208,
    altitude: 10,
    heading: 80,
    tilt: 50,
    camAltitude: 80,
    camRange: 500,
    camTilt: 50,
    camHeading: 80,
    category: 'Seen & Gewässer',
    description: 'Sieben miteinander verbundene Karstseen mit smaragdgrünem Süßwasser. Ein Geheimtipp für Stand-Up-Paddling, Safari-Bootsfahrten und ruhiges Baden.',
    highlights: ['7 verbundene Karstseen', 'Stand-Up-Paddling & traditionelle Neretva-Boote', 'Traumhafte schattige Liegewiesen'],
    iconName: 'water',
    pinColor: '#0284c7',
    glyph: '💧',
    openingHours: '24/7 frei zugänglich',
    prices: 'Freier Zugang (Bootstouren ca. 15 €)',
    cityId: 'makarska'
  },
  {
    id: 'seen-jarun-zagreb',
    name: 'Jarun-See ("Das Meer von Zagreb")',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkj',
    lat: 45.7825,
    lng: 15.9231,
    altitude: 115,
    heading: 90,
    tilt: 48,
    camAltitude: 200,
    camRange: 600,
    camTilt: 48,
    camHeading: 90,
    category: 'Seen & Gewässer',
    description: 'Beliebter Erholungs- und Badesee im Südwesten Zagrebs mit Regattastrecke, Kiesstränden, Beachvolleyball, Rollschuhbahnen und lebhaften Cafés.',
    highlights: ['Großer Badesee mit Kiesstränden', '2.000 m olympische Ruder-Regattastrecke', 'Skaterbahnen & Open-Air-Bars'],
    iconName: 'water',
    pinColor: '#0284c7',
    glyph: '💧',
    openingHours: '24/7 öffentlich geöffnet',
    prices: 'Kostenlos',
    cityId: 'zagreb'
  },

  // ==================== ATTRAKTIONEN ====================
  {
    id: 'attraktion-biokovo-skywalk',
    name: 'Skywalk Biokovo (Glasbalkon Ravna Vlaška)',
    placeId: 'ChIJ8777xP41RkcR-x9A7w-0Nkm',
    lat: 43.2928,
    lng: 17.0658,
    altitude: 1228,
    heading: 230,
    tilt: 62,
    camAltitude: 1380,
    camRange: 420,
    camTilt: 62,
    camHeading: 230,
    category: 'Attraktionen',
    description: 'Hufeisenförmige gläserne Aussichtsplattform, die 11 Meter über einen 1.228 Meter tiefen Abgrund ragt. Man geht sprichwörtlich wie auf Wolken über der Adria.',
    highlights: ['Glasboden in 1.228 m Höhe', '11 Meter Auskragung über Felswand', 'Panorama auf Hvar, Brač und Korčula'],
    iconName: 'eye',
    pinColor: '#7c3aed',
    glyph: '🎡',
    openingHours: 'Täglich 07:00 - 19:00 Uhr (Mai bis Oktober, Vorab-Online-Reservierung empfohlen)',
    prices: 'Inkludiert im Naturpark-Ticket Biokovo (ca. 8 € pro Person)',
    cityId: 'makarska'
  },
  {
    id: 'attraktion-meeresorgel-zadar',
    name: 'Meeresorgel & Sonnengruß Zadar',
    placeId: 'ChIJg_D6QW4vThMR_eYl0-s_F1E',
    lat: 44.1172,
    lng: 15.2203,
    altitude: 4,
    heading: 240,
    tilt: 50,
    camAltitude: 45,
    camRange: 280,
    camTilt: 50,
    camHeading: 240,
    category: 'Attraktionen',
    description: 'Weltweit einzigartiges Klangkunstwerk: Die Meereswellen drücken Luft durch 35 Orgelpfeifen unter weißen Marmorstufen und erzeugen mystische Melodien.',
    highlights: ['Akustische Meeresorgel von Nikola Bašić', 'Sonnengruß mit 300 Photovoltaikplatten', 'Treffpunkt für den Sonnenuntergang'],
    iconName: 'music',
    pinColor: '#7c3aed',
    glyph: '🎡',
    openingHours: '24/7 geöffnet und klangaktiv',
    prices: 'Kostenlos zugänglich',
    cityId: 'zadar'
  },
  {
    id: 'attraktion-festung-klis',
    name: 'Festung Klis (Schlüssel Dalmatiens)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkf',
    lat: 43.5606,
    lng: 16.5244,
    altitude: 360,
    heading: 190,
    tilt: 58,
    camAltitude: 480,
    camRange: 450,
    camTilt: 58,
    camHeading: 190,
    category: 'Attraktionen',
    description: 'Auf einem steilen Felsgrat zwischen den Bergen Mosor und Kozjak errichtete Festung. Sie sicherte über Jahrhunderte Split gegen Angreifer (u.a. Game of Thrones Drehort Meereen).',
    highlights: ['Trutzige Felsfestung mit 360°-Panorama', 'Historische Uskoken-Waffenkammer', 'Game of Thrones Drehort Meereen'],
    iconName: 'castle',
    pinColor: '#7c3aed',
    glyph: '🎡',
    openingHours: 'Täglich 09:00 - 20:00 Uhr',
    prices: 'Erwachsene ca. 10 €, Kinder ca. 3 €',
    cityId: 'split'
  },

  // ==================== DENKMÄLER & KULTUR ====================
  {
    id: 'kultur-diokletianpalast-peristyl',
    name: 'Diokletianpalast & Peristyl Split',
    placeId: 'ChIJO3VfN28vThMRq_H63Xn4d9Q',
    lat: 43.5083,
    lng: 16.4402,
    altitude: 16,
    heading: 350,
    tilt: 56,
    camAltitude: 75,
    camRange: 300,
    camTilt: 56,
    camHeading: 350,
    category: 'Denkmäler & Kultur',
    description: 'Eines der am besten erhaltenen Denkmäler römischer Baukunst weltweit. Das Peristyl ist der prachtvolle zentrale Säulenhof mit einer 3.500 Jahre alten ägyptischen Sphinx.',
    highlights: ['UNESCO-Weltkulturerbe seit 1979', 'Kathedrale Sv. Duje (ursprünglich Kaisermausoleum)', 'Echte ägyptische Granitsphinx'],
    iconName: 'landmark',
    pinColor: '#b45309',
    glyph: '🗿',
    openingHours: 'Innenhöfe & Gassen 24/7 frei begehbar',
    prices: 'Palast frei; Kathedrale, Turm & Keller Kombiticket ca. 12 €',
    cityId: 'split'
  },
  {
    id: 'kultur-amphitheater-pula',
    name: 'Amphitheater von Pula (Arena)',
    placeId: 'ChIJV4rN5f8tThMRf69A7w-0Nk8',
    lat: 44.8732,
    lng: 13.8502,
    altitude: 20,
    heading: 260,
    tilt: 55,
    camAltitude: 90,
    camRange: 380,
    camTilt: 55,
    camHeading: 260,
    category: 'Denkmäler & Kultur',
    description: 'Sechstgrößte römische Arena weltweit und das einzige antike Amphitheater mit noch komplett erhaltener äußerer Vierstöckigkeit. Platz für 23.000 Zuschauer bei Gladiatorenkämpfen.',
    highlights: ['Komplett erhaltene 32 Meter hohe Außenmauer', 'Unterirdische Gladiatorengänge mit Ölmuseum', 'Spektakuläre Open-Air-Konzerte'],
    iconName: 'monument',
    pinColor: '#b45309',
    glyph: '🗿',
    openingHours: 'Täglich 08:00 - 21:00 Uhr (Sommer)',
    prices: 'Erwachsene: ca. 10 €, Kinder & Studenten: ca. 5 €',
    cityId: 'pula'
  },
  {
    id: 'kultur-kathedrale-sibenik',
    name: 'Kathedrale des Hl. Jakob (Šibenik)',
    placeId: 'ChIJN6_P5PItThMRo9cO7V84N84',
    lat: 43.7358,
    lng: 15.8892,
    altitude: 18,
    heading: 120,
    tilt: 56,
    camAltitude: 80,
    camRange: 320,
    camTilt: 56,
    camHeading: 120,
    category: 'Denkmäler & Kultur',
    description: 'Meisterwerk der Renaissance von Juraj Dalmatinac. Weltweit die einzige Kathedrale, die ausschließlich aus kunstvoll verzapften Kalkstein- und Marmorplatten ohne Mörtel erbaut wurde.',
    highlights: ['UNESCO-Weltkulturerbe', 'Fassade mit 71 aus Stein gemeißelten Charakterköpfen', 'Gewölbedach komplett aus massivem Stein'],
    iconName: 'church',
    pinColor: '#b45309',
    glyph: '🗿',
    openingHours: 'Täglich 08:30 - 20:00 Uhr',
    prices: 'Eintritt ca. 5 € (inkl. Interpretationszentrum)',
    cityId: 'sibenik'
  },

  // ==================== SEHENSWÜRDIGKEITEN ====================
  {
    id: 'sehenswuerdigkeit-stadtmauer-dubrovnik',
    name: 'Stadtmauer von Dubrovnik',
    placeId: 'ChIJ2-9_4W8vThMR_8w82mR1k1s',
    lat: 42.6421,
    lng: 18.1075,
    altitude: 35,
    heading: 130,
    tilt: 55,
    camAltitude: 120,
    camRange: 420,
    camTilt: 55,
    camHeading: 130,
    category: 'Sehenswürdigkeiten',
    description: 'Eine der besterhaltenen Wehranlagen Europas. Der 1.940 Meter lange Rundgang auf der Mauer bietet atemberaubende Blicke über rote Dächer, Wehrtürme und die blaue Adria.',
    highlights: ['1.940 m ununterbrochener Wehrgang', 'Festung Minčeta & Festung Bokar', 'UNESCO-Weltkulturerbe seit 1979'],
    iconName: 'castle',
    pinColor: '#d97706',
    glyph: '🏛️',
    openingHours: 'Täglich 08:00 - 19:30 Uhr (Sommer)',
    prices: 'Erwachsene ca. 35 € (inkl. Festung Lovrijenac & Dubrovnik Pass Ermäßigung)',
    cityId: 'dubrovnik'
  },
  {
    id: 'sehenswuerdigkeit-euphrasius-basilika',
    name: 'Euphrasius-Basilika (Poreč)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkp',
    lat: 45.2286,
    lng: 13.5936,
    altitude: 15,
    heading: 300,
    tilt: 54,
    camAltitude: 70,
    camRange: 320,
    camTilt: 54,
    camHeading: 300,
    category: 'Sehenswürdigkeiten',
    description: 'Frühchristlicher Kirchenkomplex aus dem 6. Jahrhundert mit weltweit berühmten byzantinischen Goldmosaiken, die Maria und Heilige in funkelnder Pracht darstellen.',
    highlights: ['UNESCO-Weltkulturerbe', 'Goldglänzende Original-Mosaike aus dem 6. Jh.', 'Glockenturmbesteigung mit Adriablick'],
    iconName: 'church',
    pinColor: '#d97706',
    glyph: '🏛️',
    openingHours: 'Mo-Sa 09:00 - 18:00 Uhr, So nach den Gottesdiensten',
    prices: 'Eintritt ca. 7 € (inkl. Glockenturm & Museum)',
    cityId: 'rovinj'
  },
  {
    id: 'sehenswuerdigkeit-altstadt-trogir',
    name: 'Historische Insel-Altstadt Trogir',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkt',
    lat: 43.5175,
    lng: 16.2514,
    altitude: 12,
    heading: 10,
    tilt: 52,
    camAltitude: 75,
    camRange: 360,
    camTilt: 52,
    camHeading: 10,
    category: 'Sehenswürdigkeiten',
    description: 'Mittelalterliche Museumsstadt auf einer kleinen Insel zwischen Festland und Insel Čiovo. Gilt als besterhaltenes romanisch-gotisches Bauensemble Mitteleuropas.',
    highlights: ['Radovan-Portal der St.-Laurentius-Kathedrale', 'Festung Kamerlengo an der Uferpromenade', 'UNESCO-Weltkulturerbe seit 1997'],
    iconName: 'castle',
    pinColor: '#d97706',
    glyph: '🏛️',
    openingHours: '24/7 frei begehbar',
    prices: 'Altstadt frei, Kamerlengo-Festung ca. 5 €',
    cityId: 'split'
  },

  // ==================== STRÄNDE ====================
  {
    id: 'strand-zlatni-rat-bol',
    name: 'Zlatni Rat (Goldenes Horn, Brač)',
    placeId: 'ChIJN6_P5PItThMRo9cO7V84N8H',
    lat: 43.2558,
    lng: 16.6342,
    altitude: 5,
    heading: 180,
    tilt: 52,
    camAltitude: 80,
    camRange: 420,
    camTilt: 52,
    camHeading: 180,
    category: 'Strände',
    description: 'Das Wahrzeichen Kroatiens: Eine feine weiße Kieszunge ragt rund 500 Meter ins türkisfarbene Meer. Die Spitze ändert je nach Wind und Strömung ihre Form.',
    highlights: ['Wandernde Strandspitze je nach Meeresströmung', 'Surfer- & Kiter-Paradies bei Maestral-Wind', 'Schattiger Pinienwald mit Strandbars'],
    iconName: 'palmtree',
    pinColor: '#06b6d4',
    glyph: '🏖️',
    openingHours: '24/7 frei zugänglich',
    prices: 'Freier Zugang (Parkplatz vor Ort ca. 10-15 €/Tag)',
    cityId: 'hvar'
  },
  {
    id: 'strand-punta-rata-brela',
    name: 'Punta Rata & Brela-Felsen (Makarska)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkd',
    lat: 43.3711,
    lng: 16.9292,
    altitude: 8,
    heading: 230,
    tilt: 52,
    camAltitude: 70,
    camRange: 350,
    camTilt: 52,
    camHeading: 230,
    category: 'Strände',
    description: 'Vom Forbes Magazin unter die schönsten Strände der Welt gewählt. Weißer Kieselstrand, kristallklares Wasser und der fotogene Brela-Felsen mit grünen Kiefern im Meer.',
    highlights: ['Berühmter Brela-Felsen im Wasser', 'Klares Wasser mit Blaue Flagge', 'Schattige Pinienpromenade bis Baska Voda'],
    iconName: 'palmtree',
    pinColor: '#06b6d4',
    glyph: '🏖️',
    openingHours: '24/7 frei zugänglich',
    prices: 'Freier Zugang',
    cityId: 'makarska'
  },
  {
    id: 'strand-banje-dubrovnik',
    name: 'Banje Beach (Dubrovnik)',
    placeId: 'ChIJT4-f6G4vThMRw8kL588_w8p',
    lat: 42.6416,
    lng: 18.1158,
    altitude: 6,
    heading: 275,
    tilt: 52,
    camAltitude: 70,
    camRange: 320,
    camTilt: 52,
    camHeading: 275,
    category: 'Strände',
    description: 'Der berühmteste Stadtstrand Dubrovniks mit direktem Postkartenblick auf die alte Stadtmauer und den alten Hafen. Kieselstrand mit Liegenverleih und Lounge-Club.',
    highlights: ['Spektakulärer Blick auf die Altstadtmauer', 'Kristallklares Wasser für erfrischende Abkühlung', 'Jet-Ski, Parasailing & Beach-Club'],
    iconName: 'palmtree',
    pinColor: '#06b6d4',
    glyph: '🏖️',
    openingHours: '24/7 frei zugänglich (Beach Club 10:00 - 01:00)',
    prices: 'Freier Strandzugang (Liegen/Schirme separat gegen Gebühr)',
    cityId: 'dubrovnik'
  },
  {
    id: 'strand-bacvice-split',
    name: 'Bačvice Sandstrand (Split)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nks',
    lat: 43.5042,
    lng: 16.4475,
    altitude: 5,
    heading: 160,
    tilt: 50,
    camAltitude: 65,
    camRange: 340,
    camTilt: 50,
    camHeading: 160,
    category: 'Strände',
    description: 'Der legendäre Sandstrand von Split in Gehweite zur Riva. Hier wurde der traditionelle dalmatinische Ballsport Picigin erfunden, der im seichten Wasser akrobatisch gespielt wird.',
    highlights: ['Feiner Sandstrand & flach abfallendes Wasser', 'Heimat des traditionellen Picigin-Spiels', 'Cafés & Restaurants direkt an der Uferpromenade'],
    iconName: 'palmtree',
    pinColor: '#06b6d4',
    glyph: '🏖️',
    openingHours: '24/7 frei zugänglich',
    prices: 'Kostenlos',
    cityId: 'split'
  },
  {
    id: 'strand-sakarun-dugi-otok',
    name: 'Sakarun Bucht (Karibik der Adria / Zadar)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nku',
    lat: 44.1350,
    lng: 14.8692,
    altitude: 5,
    heading: 210,
    tilt: 50,
    camAltitude: 70,
    camRange: 450,
    camTilt: 50,
    camHeading: 210,
    category: 'Strände',
    description: 'Eine 800 Meter lange Bucht auf der Insel Dugi Otok bei Zadar mit weißem Sand und leuchtend türkisem, flachem Wasser wie in der Karibik.',
    highlights: ['Weißer Sandboden & türkises Wasser', 'Flacher Einstieg perfekt für Kinder', 'Kiefernwälder im Hintergrund'],
    iconName: 'palmtree',
    pinColor: '#06b6d4',
    glyph: '🏖️',
    openingHours: '24/7 frei zugänglich',
    prices: 'Freier Zugang',
    cityId: 'zadar'
  },

  // ==================== FREIZEITPARKS ====================
  {
    id: 'park-aquapark-istralandia',
    name: 'Aquapark Istralandia (Novigrad / Istrien)',
    placeId: 'ChIJO3VfN28vThMRq_H63Xn4d9R',
    lat: 45.3482,
    lng: 13.6190,
    altitude: 40,
    heading: 170,
    tilt: 55,
    camAltitude: 160,
    camRange: 500,
    camTilt: 55,
    camHeading: 170,
    category: 'Freizeitparks',
    description: 'Einer der besten Wasserparks Europas auf 81.000 m². Über 20 Rutschen, riesiges Wellenbecken, Kinder-Piratenschloss und bunte Animationen.',
    highlights: ['2.500 m² großes Wellenbecken', 'Free-Fall-Rutsche aus 27 m Höhe', 'Kinderburg & flache Sprühzonen'],
    iconName: 'ferris-wheel',
    pinColor: '#ec4899',
    glyph: '🎢',
    openingHours: 'Täglich 10:00 - 18:00 Uhr (Saison Juni bis September)',
    prices: 'Ganztagesticket Erwachsene: ca. 34 €, Kinder (1,00 - 1,40 m): ca. 27 €, Kinder unter 1 m frei',
    contact: 'Tel: +385 52 864 200 | info@istralandia.com',
    cityId: 'rovinj'
  },
  {
    id: 'park-dalmaland-biograd',
    name: 'Dalmaland Freizeit- & Wasserpark (Biograd / Zadar)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkx',
    lat: 43.9292,
    lng: 15.4631,
    altitude: 35,
    heading: 120,
    tilt: 55,
    camAltitude: 140,
    camRange: 480,
    camTilt: 55,
    camHeading: 120,
    category: 'Freizeitparks',
    description: 'Kombinierter Themen- und Wasserpark mit Achterbahnen, Riesenrad, Piratenschiff, interaktiven Wasserlandschaften und Themenwelten (Weltall, Piraten, Wilder Westen).',
    highlights: ['Achterbahn "Big Blue" & 30m-Riesenrad', 'Wasserpark mit Looping- und Reifenrutschen', 'Themenwelten für die ganze Familie'],
    iconName: 'ferris-wheel',
    pinColor: '#ec4899',
    glyph: '🎢',
    openingHours: 'Täglich 10:00 - 19:00 Uhr (Juni bis September)',
    prices: 'Erwachsene Kombi (Themen- + Aquapark): ca. 36 €, Kinder: ca. 30 €',
    contact: 'Tel: +385 23 630 377 | info@dalmaland.com',
    cityId: 'zadar'
  },
  {
    id: 'park-aquarium-pula',
    name: 'Aquarium Pula (Historische Festung Verudela)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkq',
    lat: 44.8322,
    lng: 13.8344,
    altitude: 30,
    heading: 290,
    tilt: 55,
    camAltitude: 110,
    camRange: 380,
    camTilt: 55,
    camHeading: 290,
    category: 'Freizeitparks',
    description: 'Untergebracht in der 1886 erbauten österreichisch-ungarischen Festung Verudela. Zeigt über 250 Meeresarten der Adria, Schildkröten-Rettungsstation und Haie.',
    highlights: ['Hai-Becken im ehemaligen Festungskeller', 'Meeresschildkröten-Rehabilitationszentrum', 'Tropische Korallenriffe & Streichelbecken'],
    iconName: 'fish',
    pinColor: '#ec4899',
    glyph: '🎢',
    openingHours: 'Täglich 09:00 - 21:00 Uhr (Sommer)',
    prices: 'Erwachsene: ca. 20 €, Kinder 3-18 Jahre: ca. 14 €, Kinder unter 3 frei',
    contact: 'Tel: +385 52 381 402 | infos@aquarium.hr',
    cityId: 'pula'
  },

  // ==================== SCHWIMMBÄDER & THERMEN ====================
  {
    id: 'therme-tuhelj',
    name: 'Terme Tuhelj (Wasserplanet & Thermalquellen Zagorje)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkt',
    lat: 46.0694,
    lng: 15.7878,
    altitude: 160,
    heading: 45,
    tilt: 54,
    camAltitude: 220,
    camRange: 450,
    camTilt: 54,
    camHeading: 45,
    category: 'Schwimmbäder & Thermen',
    description: 'Größtes Bade- und Thermenresort Kroatiens bei Zagreb mit dem "Vodeni Planet" (Wasserplanet), Thermalmineralwasser, 8 Innen- und Außenbecken sowie der weltberühmten Saunalandschaft.',
    highlights: ['5.000 m² Wasserfläche & Thermalbecken', 'Thermal-Heilschlamm (Fango)', 'Wellenbad, Strömungskanal & Röhrenrutschen'],
    iconName: 'waves',
    pinColor: '#0ea5e9',
    glyph: '🏊',
    openingHours: 'Täglich 08:00 - 22:00 Uhr (Freitags & Samstags bis 23:00)',
    prices: 'Tageskarte Erwachsene Mo-Fr: 17 €, Sa-So: 21 € | Kinder (5-15): 11 € - 14 €',
    contact: 'Tel: +385 49 203 750 | info@terme-tuhelj.hr',
    cityId: 'zagreb'
  },
  {
    id: 'therme-krapinske-toplice',
    name: 'Aquae Vivae Thermen (Krapinske Toplice)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkw',
    lat: 46.0894,
    lng: 15.8458,
    altitude: 175,
    heading: 30,
    tilt: 54,
    camAltitude: 240,
    camRange: 420,
    camTilt: 54,
    camHeading: 30,
    category: 'Schwimmbäder & Thermen',
    description: 'Modernes Thermalbad mit über 160 Wasserattraktionen, Naturquellwasser mit 34°C, Wellenbecken, Rutschen und einem einzigartigen Tauchbecken (4,5 m tief).',
    highlights: ['Natürliches Heilthermalwasser mit 34°C', '4,5 Meter tiefes Tauchbecken mit Sichtfenster', 'Kombinierte Innen- und Außenbecken'],
    iconName: 'waves',
    pinColor: '#0ea5e9',
    glyph: '🏊',
    openingHours: 'Täglich 09:00 - 21:00 Uhr',
    prices: 'Tageskarte Erwachsene: ca. 16 €, Kinder (6-15): ca. 10 €',
    contact: 'Tel: +385 49 501 501 | info@aquae-vivae.hr',
    cityId: 'zagreb'
  },
  {
    id: 'therme-bazeni-poljud-split',
    name: 'Schwimmstadion Bazeni Poljud (Split)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nko',
    lat: 43.5217,
    lng: 16.4292,
    altitude: 20,
    heading: 220,
    tilt: 52,
    camAltitude: 90,
    camRange: 380,
    camTilt: 52,
    camHeading: 220,
    category: 'Schwimmbäder & Thermen',
    description: 'Großer Sport- und Hallenbadkomplex am Stadion Poljud mit 50m-Olympia-Hallenbecken, Sprungturmbecken, Freizeitbecken und Saunabereich für Freizeitschwimmer.',
    highlights: ['50 Meter Olympia-Hallenbecken', 'Wasserball- & Sprungbecken', 'Fitness- & Wellnessbereich'],
    iconName: 'waves',
    pinColor: '#0ea5e9',
    glyph: '🏊',
    openingHours: 'Mo-Fr 06:00 - 22:00 Uhr, Sa-So 08:00 - 20:00 Uhr',
    prices: 'Einzeleintritt ca. 4,50 €, 10er-Karte ca. 35 €',
    contact: 'Tel: +385 21 381 289',
    cityId: 'split'
  },
  {
    id: 'therme-bazeni-kantrida-rijeka',
    name: 'Badezentrum Bazeni Kantrida (Rijeka / Kvarner)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkr',
    lat: 45.3486,
    lng: 14.3739,
    altitude: 10,
    heading: 190,
    tilt: 52,
    camAltitude: 75,
    camRange: 350,
    camTilt: 52,
    camHeading: 190,
    category: 'Schwimmbäder & Thermen',
    description: 'Spektakuläre Schwimmanlage direkt am Meer mit Cabriodach (öffnet sich bei Sonnenschein), Meerwasserbecken, Hallenbädern und direktem Zugang zum Kiesstrand.',
    highlights: ['Hallenbecken mit auffahrbarem Cabriodach', 'Beheiztes 50m-Olympia-Meerwasserbecken', 'Direkter Zugang zum Adria-Kiesstrand'],
    iconName: 'waves',
    pinColor: '#0ea5e9',
    glyph: '🏊',
    openingHours: 'Täglich 07:00 - 22:00 Uhr',
    prices: 'Einzeleintritt ca. 5 €, Kinder & Senioren: ca. 3 €',
    contact: 'Tel: +385 51 666 600',
    cityId: 'rovinj'
  },

  // ==================== TANKSTELLEN ====================
  {
    id: 'tankstelle-ina-dubrovnik-gruz',
    name: 'INA Tankstelle Dubrovnik (Hafen Gruž)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkg',
    lat: 42.6583,
    lng: 18.0875,
    altitude: 10,
    heading: 110,
    tilt: 50,
    camAltitude: 60,
    camRange: 280,
    camTilt: 50,
    camHeading: 110,
    category: 'Tankstellen',
    description: 'Zentrale INA 24-Stunden-Tankstelle am Fährhafen Gruž mit Eurosuper 95, Eurodiesel, Autogas (LPG), Reifendruck-Station und Shop.',
    highlights: ['24/7 durchgehend geöffnet', 'Direkt an der D8 Küstenstraße / Fährhafen', 'Bistro & Shop mit Kaffeespezialitäten'],
    iconName: 'fuel',
    pinColor: '#e11d48',
    glyph: '⛽',
    openingHours: '24 Stunden / 7 Tage geöffnet (Non-Stop)',
    prices: 'Spritpreise aktuell reguliert',
    fuelPrices: { super95: '1,49 €/L', diesel: '1,42 €/L', lpg: '0,88 €/L' },
    contact: 'Tel: +385 20 418 200',
    cityId: 'dubrovnik'
  },
  {
    id: 'tankstelle-petrol-split-poljud',
    name: 'Petrol Tankstelle Split (Poljud)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkh',
    lat: 43.5236,
    lng: 16.4358,
    altitude: 15,
    heading: 150,
    tilt: 50,
    camAltitude: 65,
    camRange: 290,
    camTilt: 50,
    camHeading: 150,
    category: 'Tankstellen',
    description: 'Moderne Petrol-Tankstelle nahe dem Stadtzentrum und Stadion mit Q-Max Kraftstoffen, AdBlue-Zapfsäule, Staubsauger und Backshop.',
    highlights: ['24 Stunden Service', 'Q-Max 95 & Q-Max Diesel', 'Kaffee & Snack-Shop'],
    iconName: 'fuel',
    pinColor: '#e11d48',
    glyph: '⛽',
    openingHours: '24 Stunden geöffnet',
    prices: 'Offizielle Tankstellenpreise Kroatien',
    fuelPrices: { super95: '1,48 €/L', diesel: '1,41 €/L', lpg: '0,87 €/L' },
    contact: 'Tel: +385 21 380 440',
    cityId: 'split'
  },
  {
    id: 'tankstelle-ina-zadar-gazenica',
    name: 'INA Tankstelle Zadar (Hafen Gaženica)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkn',
    lat: 44.0928,
    lng: 15.2631,
    altitude: 12,
    heading: 200,
    tilt: 50,
    camAltitude: 60,
    camRange: 300,
    camTilt: 50,
    camHeading: 200,
    category: 'Tankstellen',
    description: 'Große 24h-Haupttankstelle beim modernen Fährhafen Zadar-Gaženica mit LKW-Spuren, PKW-Waschanlage und großem Reiseshop.',
    highlights: ['24h geöffnet', 'Ausfahrt Autobahnanschluss A1 & Fährterminal', 'Kaffee, Snacks & Autowäsche'],
    iconName: 'fuel',
    pinColor: '#e11d48',
    glyph: '⛽',
    openingHours: '24 Stunden geöffnet',
    prices: 'Günstige Standardpreise',
    fuelPrices: { super95: '1,49 €/L', diesel: '1,42 €/L', lpg: '0,89 €/L' },
    contact: 'Tel: +385 23 340 100',
    cityId: 'zadar'
  },
  {
    id: 'tankstelle-crodux-zagreb-lucko',
    name: 'Petrol / Crodux Tankstelle Zagreb (Lučko A1)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkl',
    lat: 45.7608,
    lng: 15.8742,
    altitude: 120,
    heading: 80,
    tilt: 50,
    camAltitude: 160,
    camRange: 350,
    camTilt: 50,
    camHeading: 80,
    category: 'Tankstellen',
    description: 'Wichtigste Autobahntankstelle an der Mautstation Lučko (Einfahrt A1 Dalmatina Richtung Küste) mit Schnellladesäulen für E-Autos.',
    highlights: ['24h Raststätte & Tankstelle', 'HPC Ultra-Schnellladestationen (300 kW)', 'Restaurant & Reisebedarf'],
    iconName: 'fuel',
    pinColor: '#e11d48',
    glyph: '⛽',
    openingHours: '24 Stunden / 365 Tage im Jahr geöffnet',
    prices: 'Autobahntarif',
    fuelPrices: { super95: '1,52 €/L', diesel: '1,45 €/L', lpg: '0,91 €/L' },
    contact: 'Tel: +385 1 653 0900',
    cityId: 'zagreb'
  },
  {
    id: 'tankstelle-ina-makarska',
    name: 'INA Tankstelle Makarska (D8 Küstenstraße)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkx',
    lat: 43.3006,
    lng: 17.0256,
    altitude: 25,
    heading: 140,
    tilt: 50,
    camAltitude: 70,
    camRange: 300,
    camTilt: 50,
    camHeading: 140,
    category: 'Tankstellen',
    description: 'Zentrale Tankstelle an der Magistrale D8 in Makarska mit Panoramablick auf das Biokovo-Gebirge, Euro95, Diesel und Autogas.',
    highlights: ['24h geöffnet in der Hochsaison', 'Direkt an der D8 Riviera-Straße', 'Reifendruck, Eis & Erfrischungen'],
    iconName: 'fuel',
    pinColor: '#e11d48',
    glyph: '⛽',
    openingHours: '24 Stunden geöffnet',
    prices: 'Standardtarif Küste',
    fuelPrices: { super95: '1,49 €/L', diesel: '1,42 €/L', lpg: '0,88 €/L' },
    contact: 'Tel: +385 21 611 122',
    cityId: 'makarska'
  },

  // ==================== KRANKENHÄUSER ====================
  {
    id: 'klinik-ob-dubrovnik',
    name: 'Allgemeines Krankenhaus Dubrovnik (Opća Bolnica)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkx',
    lat: 42.6481,
    lng: 18.0833,
    altitude: 45,
    heading: 230,
    tilt: 52,
    camAltitude: 95,
    camRange: 350,
    camTilt: 52,
    camHeading: 230,
    category: 'Krankenhäuser',
    description: 'Modernes Schwerpunktkrankenhaus der Region Dubrovnik-Neretva mit zentraler 24/7 Notaufnahme (Hitni prijem), Chirurgie, Pädiatrie und Hubschrauberlandeplatz.',
    highlights: ['24/7 Zentrale Notaufnahme (OHBP)', 'Notruf 112 & Rettungsdienst 194', 'Englisch- und deutschsprachiges Personal'],
    iconName: 'hospital',
    pinColor: '#dc2626',
    glyph: '🏥',
    openingHours: 'Notaufnahme: 24 Stunden / 7 Tage geöffnet (Non-Stop)',
    prices: 'EU-Krankenversicherungskarte (EHIC) wird akzeptiert',
    contact: 'Notruf: 194 oder 112 | Tel: +385 20 431 777',
    cityId: 'dubrovnik'
  },
  {
    id: 'klinik-kbc-split-firule',
    name: 'Universitätsklinikum Split (KBC Split - Firule)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nky',
    lat: 43.5036,
    lng: 16.4578,
    altitude: 35,
    heading: 170,
    tilt: 52,
    camAltitude: 85,
    camRange: 380,
    camTilt: 52,
    camHeading: 170,
    category: 'Krankenhäuser',
    description: 'Größtes medizinisches Zentrum Dalmatiens mit maximaler Versorgungsstufe. Voll ausgestattete Notfallchirurgie, Kinderklinik, Kardiologie und Intensivmedizin.',
    highlights: ['24/7 Notfallzentrum Dalmatiens', 'Traumazentrum & Kinderklinik', 'Notruf 194 / 112'],
    iconName: 'hospital',
    pinColor: '#dc2626',
    glyph: '🏥',
    openingHours: 'Notaufnahme: 24/7 Non-Stop geöffnet',
    prices: 'Notfallbehandlung mit EHIC / Auslandskrankenversicherung',
    contact: 'Notruf: 194 oder 112 | Zentrale: +385 21 556 111',
    cityId: 'split'
  },
  {
    id: 'klinik-kbc-zagreb-rebro',
    name: 'Universitätsklinikum Zagreb (KBC Zagreb - Rebro)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkz',
    lat: 45.8242,
    lng: 16.0078,
    altitude: 160,
    heading: 140,
    tilt: 52,
    camAltitude: 220,
    camRange: 450,
    camTilt: 52,
    camHeading: 140,
    category: 'Krankenhäuser',
    description: 'Das größte Krankenhaus Kroatiens mit modernster High-Tech-Medizin, Nationalem Notfallzentrum, Spezialkliniken und allen Fachabteilungen.',
    highlights: ['Führende Universitätsklinik Kroatiens', '24/7 Notfall-Zentrum', 'Modernste Diagnostik'],
    iconName: 'hospital',
    pinColor: '#dc2626',
    glyph: '🏥',
    openingHours: 'Notaufnahme: 24 Stunden geöffnet',
    prices: 'EHIC / europäische Versichertenkarte',
    contact: 'Notruf: 194 / 112 | Zentrale: +385 1 2388 888',
    cityId: 'zagreb'
  },
  {
    id: 'klinik-ob-zadar',
    name: 'Allgemeines Krankenhaus Zadar (Opća Bolnica Zadar)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkx',
    lat: 44.1106,
    lng: 15.2422,
    altitude: 20,
    heading: 100,
    tilt: 52,
    camAltitude: 80,
    camRange: 350,
    camTilt: 52,
    camHeading: 100,
    category: 'Krankenhäuser',
    description: 'Zentrales Akutkrankenhaus für die Region Zadar und die norddalmatinischen Inseln mit 24h-Unfallchirurgie und Ambulanz.',
    highlights: ['24/7 Notaufnahme', 'Zentrale Lage nahe Kolovare', 'Notruf 194 / 112'],
    iconName: 'hospital',
    pinColor: '#dc2626',
    glyph: '🏥',
    openingHours: 'Notaufnahme 24/7 geöffnet',
    prices: 'EHIC wird akzeptiert',
    contact: 'Notruf: 194 / 112 | Tel: +385 23 505 505',
    cityId: 'zadar'
  },
  {
    id: 'klinik-ob-pula',
    name: 'Allgemeines Krankenhaus Pula (Opća Bolnica Pula)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkx',
    lat: 44.8653,
    lng: 13.8647,
    altitude: 40,
    heading: 260,
    tilt: 52,
    camAltitude: 95,
    camRange: 380,
    camTilt: 52,
    camHeading: 260,
    category: 'Krankenhäuser',
    description: 'Neu erbautes, hochmodernes Regionalkrankenhaus für ganz Süd- und Westistrien mit 24h-Notfallaufnahme und Fachärzten.',
    highlights: ['Neubau mit modernster Ausstattung', '24h Notaufnahme für Urlauber & Einheimische', 'Notruf 194 / 112'],
    iconName: 'hospital',
    pinColor: '#dc2626',
    glyph: '🏥',
    openingHours: 'Notaufnahme 24/7 geöffnet',
    prices: 'EHIC / Notfallversorgung',
    contact: 'Notruf: 194 / 112 | Tel: +385 52 376 000',
    cityId: 'pula'
  },

  // ==================== APOTHEKEN ====================
  {
    id: 'apotheke-ljekarna-stradun-dubrovnik',
    name: 'Ljekarna Stradun (Alte Franziskanerapotheke)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkx',
    lat: 42.6416,
    lng: 18.1075,
    altitude: 20,
    heading: 80,
    tilt: 50,
    camAltitude: 60,
    camRange: 250,
    camTilt: 50,
    camHeading: 80,
    category: 'Apotheken',
    description: 'Eine der ältesten noch durchgehend arbeitenden Apotheken der Welt (seit 1317!). Bietet moderne Arzneimittel sowie traditionelle Kräutercremes nach Klosterrezepturen.',
    highlights: ['Gegründet 1317 im Franziskanerkloster', 'Voll ausgestattete moderne Apotheke', 'Traditionelle Rosen- & Lavendelcremes'],
    iconName: 'pill',
    pinColor: '#10b981',
    glyph: '💊',
    openingHours: 'Mo-Sa 07:00 - 20:30 Uhr, So 08:00 - 18:00 Uhr (Notdienst wechselt)',
    prices: 'Rezepte & rezeptfreie Medikamente nach EU-Standard',
    contact: 'Tel: +385 20 321 411',
    cityId: 'dubrovnik'
  },
  {
    id: 'apotheke-ljekarna-split-lucac',
    name: 'Ljekarna Lučac 24h-Notdienst (Split)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkx',
    lat: 43.5097,
    lng: 16.4444,
    altitude: 18,
    heading: 140,
    tilt: 50,
    camAltitude: 65,
    camRange: 260,
    camTilt: 50,
    camHeading: 140,
    category: 'Apotheken',
    description: 'Die offizielle 24-Stunden-Bereitschaftsapotheke in Split nahe dem Diokletianpalast. Rund um die Uhr für dringende Medikamente und Notfälle erreichbar.',
    highlights: ['24h Nacht- und Feiertagsnotdienst', 'Zentral erreichbar nahe Altstadt', 'Großes Medikamenten- und Verbandssortiment'],
    iconName: 'pill',
    pinColor: '#10b981',
    glyph: '💊',
    openingHours: '24 Stunden Non-Stop (Dežurna ljekarna)',
    prices: 'Reguläre Apothekenpreise',
    contact: 'Tel: +385 21 533 188',
    cityId: 'split'
  },
  {
    id: 'apotheke-ljekarna-zagreb-trg',
    name: 'Gradska Ljekarna Trg 24h (Zagreb)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkx',
    lat: 45.8133,
    lng: 15.9772,
    altitude: 120,
    heading: 10,
    tilt: 50,
    camAltitude: 160,
    camRange: 280,
    camTilt: 50,
    camHeading: 10,
    category: 'Apotheken',
    description: 'Zentrale 24-Stunden-Stadtapotheke direkt am Ban-Jelačić-Hauptplatz Nr. 3 in Zagreb mit durchgehendem Nachtdienstfenster.',
    highlights: ['24h Non-Stop Notdienst', 'Direkt am Hauptplatz Ban Jelačić', 'Kompetente mehrsprachige Beratung'],
    iconName: 'pill',
    pinColor: '#10b981',
    glyph: '💊',
    openingHours: '24 Stunden / 365 Tage im Jahr geöffnet',
    prices: 'Apotheken-Standardtarife',
    contact: 'Tel: +385 1 4816 159',
    cityId: 'zagreb'
  },
  {
    id: 'apotheke-ljekarna-zadar-centar',
    name: 'Ljekarna Zadar Centar (Dežurna 24h)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkx',
    lat: 44.1147,
    lng: 15.2269,
    altitude: 15,
    heading: 220,
    tilt: 50,
    camAltitude: 65,
    camRange: 260,
    camTilt: 50,
    camHeading: 220,
    category: 'Apotheken',
    description: 'Notdienst-Apotheke auf der Altstadt-Halbinsel von Zadar mit durchgehendem Bereitschaftsdienst für Medikamente und Reisebedarf.',
    highlights: ['24h Notdienstbereitschaft', 'Zentrale Halbinsellage', 'Erste Hilfe & Sonnenschutz'],
    iconName: 'pill',
    pinColor: '#10b981',
    glyph: '💊',
    openingHours: 'Täglich 00:00 - 24:00 Uhr',
    prices: 'Reguläre Preise',
    contact: 'Tel: +385 23 211 436',
    cityId: 'zadar'
  },

  // ==================== POLIZEIREVIERE ====================
  {
    id: 'polizei-postaja-dubrovnik',
    name: 'Polizeidienststelle Dubrovnik (Policijska Postaja)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkx',
    lat: 42.6517,
    lng: 18.0931,
    altitude: 30,
    heading: 160,
    tilt: 50,
    camAltitude: 75,
    camRange: 320,
    camTilt: 50,
    camHeading: 160,
    category: 'Polizeireviere',
    description: 'Hauptpolizeidienststelle der Stadt Dubrovnik mit Kriminalpolizei, Fundbüro, Touristenbetreuung und 24/7 Notrufeinsatzzentrale.',
    highlights: ['24/7 besetzte Polizeistation', 'Polizei-Notruf: 192 (oder EU-Notruf 112)', 'Hilfe bei Passverlust, Diebstahl & Unfällen'],
    iconName: 'shield',
    pinColor: '#3b82f6',
    glyph: '👮',
    openingHours: '24 Stunden / 7 Tage geöffnet (Non-Stop)',
    prices: 'Kostenlose polizeiliche Hilfeleistung',
    contact: 'Polizei-Notruf: 192 | Dienststelle: +385 20 444 111',
    cityId: 'dubrovnik'
  },
  {
    id: 'polizei-postaja-split',
    name: 'I. Polizeidienststelle Split (Policijska Postaja Centar)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkx',
    lat: 43.5133,
    lng: 16.4422,
    altitude: 20,
    heading: 190,
    tilt: 50,
    camAltitude: 70,
    camRange: 300,
    camTilt: 50,
    camHeading: 190,
    category: 'Polizeireviere',
    description: 'Zentrale Polizeidienststelle der Stadt Split unweit der Altstadt für Stadtgebiet, Hafen und Touristenbetreuung.',
    highlights: ['24/7 Notfalldienststelle', 'Polizei-Notruf: 192', 'Fremdsprachen-Assistenz für Touristen'],
    iconName: 'shield',
    pinColor: '#3b82f6',
    glyph: '👮',
    openingHours: '24 Stunden geöffnet',
    prices: 'Kostenlos',
    contact: 'Polizei-Notruf: 192 | Dienststelle: +385 21 307 111',
    cityId: 'split'
  },
  {
    id: 'polizei-postaja-zagreb-centar',
    name: 'I. Polizeidienststelle Zagreb (Centar)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkx',
    lat: 45.8111,
    lng: 15.9733,
    altitude: 120,
    heading: 30,
    tilt: 50,
    camAltitude: 160,
    camRange: 320,
    camTilt: 50,
    camHeading: 30,
    category: 'Polizeireviere',
    description: 'Zentrale Polizeidienststelle im Herzen Zagrebs für Innenstadt, diplomatische Vertretungen und öffentliche Sicherheit.',
    highlights: ['24/7 Einsatzzentrale', 'Polizei-Notruf: 192', 'Zentrale Lage nahe Zrinjevac-Park'],
    iconName: 'shield',
    pinColor: '#3b82f6',
    glyph: '👮',
    openingHours: '24 Stunden geöffnet',
    prices: 'Kostenlos',
    contact: 'Polizei-Notruf: 192 | Dienststelle: +385 1 4563 111',
    cityId: 'zagreb'
  },
  {
    id: 'polizei-postaja-zadar',
    name: 'I. Polizeidienststelle Zadar (Policijska Postaja)',
    placeId: 'ChIJ5777xP41RkcR-x9A7w-0Nkx',
    lat: 44.1178,
    lng: 15.2356,
    altitude: 18,
    heading: 240,
    tilt: 50,
    camAltitude: 70,
    camRange: 300,
    camTilt: 50,
    camHeading: 240,
    category: 'Polizeireviere',
    description: 'Zuständige Dienststelle für Zadar und Küstenstreifen mit 24h-Wache und Streifendienst.',
    highlights: ['24/7 erreichbar', 'Notruf: 192', 'Sicherheit im Stadt- und Hafengebiet'],
    iconName: 'shield',
    pinColor: '#3b82f6',
    glyph: '👮',
    openingHours: '24 Stunden geöffnet',
    prices: 'Kostenlos',
    contact: 'Polizei-Notruf: 192 | Tel: +385 23 345 111',
    cityId: 'zadar'
  }
];

// Helper: Berechnet POIs im 25 km Umkreis von einem gegebenen Standort
export function getPoisInRadius(
  centerLat: number,
  centerLng: number,
  radiusKm: number = 25,
  activeCategories: string[] = []
): { cities: Landmark[]; filteredPois: Landmark[]; allInRadius: Landmark[] } {
  // Haversine
  const calcDist = (lat: number, lng: number): number => {
    const R = 6371;
    const dLat = ((lat - centerLat) * Math.PI) / 180;
    const dLng = ((lng - centerLng) * Math.PI) / 180;
    const a =
      Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos((centerLat * Math.PI) / 180) *
        Math.cos((lat * Math.PI) / 180) *
        Math.sin(dLng / 2) *
        Math.sin(dLng / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return Math.round(R * c * 10) / 10;
  };

  const allWithDist = ALL_CROATIA_POIS.map((poi) => ({
    ...poi,
    distanceKm: calcDist(poi.lat, poi.lng)
  }));

  const allInRadius = allWithDist.filter((p) => p.distanceKm <= radiusKm);

  // Städte im 25 km Umkreis (oder nächstgelegene Städte, falls im Umkreis keine ist)
  let cities = allInRadius.filter((p) => p.category === 'Städte');
  if (cities.length === 0) {
    // Falls Aufenthaltsort etwas abseits liegt, zeige die 3 nächstgelegenen Städte
    cities = [...allWithDist]
      .filter((p) => p.category === 'Städte')
      .sort((a, b) => (a.distanceKm || 0) - (b.distanceKm || 0))
      .slice(0, 3);
  }

  // Gefilterte POIs: Nur jene Kategorien, die der Nutzer explizit ausgewählt hat!
  const filteredPois = allInRadius.filter(
    (p) => p.category !== 'Städte' && activeCategories.includes(p.category)
  );

  return { cities, filteredPois, allInRadius };
}
